## Question 1 (10 Marks)
## Load the House Price dataset and display:

## Dataset shape
## First 10 rows
## 5 random samples

In [124]:
import warnings 
warnings.filterwarnings("ignore")

import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.model_selection import train_test_split,cross_val_score 
from sklearn.pipeline import Pipeline 
from sklearn.compose import ColumnTransformer 
from sklearn.impute import SimpleImputer 
from sklearn.preprocessing import StandardScaler,OneHotEncoder 
from sklearn.linear_model import LinearRegression,SGDRegressor 
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error

In [125]:
df = pd.read_csv('house_price_regression_dataset.csv')
df

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06
...,...,...,...,...,...,...,...,...
995,3261,4,1,1978,2.165110,2,10,7.014940e+05
996,3179,1,2,1999,2.977123,1,10,6.837232e+05
997,2606,4,2,1962,4.055067,0,2,5.720240e+05
998,4723,5,2,1950,1.930921,0,7,9.648653e+05
999,3268,4,2,1983,3.108790,2,2,7.425993e+05

In [126]:
print("Shape :", df.shape)

display(df.head(10))

df.sample(5)

Shape : (1000, 8)

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06
5,3944,5,3,1990,2.475930,2,8,8.797970e+05
6,3671,1,2,2012,4.911960,0,1,8.144279e+05
7,3419,1,1,1972,2.805281,1,1,7.034131e+05
8,630,3,3,1997,1.014286,1,8,1.738750e+05
9,2185,4,2,1981,3.941604,2,5,5.041765e+05

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
863,3230,3,1,2011,2.960133,2,7,734110.024360
867,4376,2,3,1997,4.383541,0,4,953339.730645
61,2481,3,1,1991,0.703937,0,1,509725.550655
536,1167,1,1,1967,0.944317,2,10,219652.598014
42,3112,2,3,1980,2.656670,0,9,666733.473462

---
## Question 2 (10 Marks)

Handle missing values and perform feature engineering:
- Impute missing numerical values using `SimpleImputer` with mean strategy
- Impute missing categorical values using most frequent strategy
- Drop columns with more than 50% missing values
- Perform train-test split with `test_size=0.2` and `random_state=42`

Display the shape of final train and test sets.

In [127]:
# OR
#df.isnull().sum()
half_count = len(df) // 2 
df = df.dropna(thresh=half_count, axis=1) 

X = df.drop(columns=['House_Price'], axis=1) 
y = df['House_Price'] 

num_feature  = X.select_dtypes(include=['int64', 'float64']).columns 
cat_feature  = X.select_dtypes(include=['object']).columns 

if len(num_feature) > 0: 
    num_imputer = SimpleImputer(strategy="mean")
    X[num_feature] = num_imputer.fit_transform(X[num_feature]) 


if len(cat_feature) > 0: 
    cat_imputer = SimpleImputer(strategy='most_frequent')
    X[cat_feature] = cat_imputer.fit_transform(X[cat_feature])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

print("X_train : ", X_train.shape)
print("X_test : ", X_test.shape) 
print("y_train : ", y_train.shape) 
print("y_test : ", y_test.shape)

X_train :  (800, 7)
X_test :  (200, 7)
y_train :  (800,)
y_test :  (200,)

In [128]:
#df.isnull().sum()
count = df.isnull().mean() 
df = df.drop(columns=count[count > 0.5].index)

X = df.drop(['House_Price'], axis=1) 
y = df['House_Price'] 


num_feature  = X.select_dtypes(include=['int64', 'float64']).columns 
cat_feature  = X.select_dtypes(include=['object']).columns 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)


if len(num_feature) > 0: 
    num_imputer = SimpleImputer(strategy="mean")
    X_train[num_feature] = num_imputer.fit_transform(X_train[num_feature]) 
    X_test[num_feature] = num_imputer.fit_transform(X_test[num_feature]) 


if len(cat_feature) > 0: 
    cat_imputer = SimpleImputer(strategy="most_frequent")
    X_train[cat_feature] = cat_imputer.fit_transform(X_train[cat_feature])
    X_test[cat_feature] = cat_imputer.fit_transform(X_test[cat_feature])


print("X_train : ", X_train.shape)
print("X_test : ", X_test.shape) 
print("y_train : ", y_train.shape) 
print("y_test : ", y_test.shape)

X_train :  (800, 7)
X_test :  (200, 7)
y_train :  (800,)
y_test :  (200,)

---
## Question 3 (20 Marks)

Implement **Simple Linear Regression** using **only NumPy** (no Scikit-Learn allowed):
- Compute slope (`m`) and intercept (`c`) using the Batch Gradient Descent
- Predict values for the test set
- Print the learned `m` and `c` values

Use `Square_Footage` as feature (X) and `House_Price` as target (y).

In [157]:
#actual 

X = X_train["Square_Footage"].values 
y = y_train.values 

X_mean = X.mean() 
X_std = X.std() 
X = (X-X_mean) / X_std 

m = 0.0
c = 0.0 
learning_rate = 0.01 
iterations = 10000
n = len(X)


for i in range(iterations): 
    y_pred = m * X + c
    error = y_pred - y 
    
    dm = 0
    dc = 0 

    for j in range(n): 
        dm += error[j] * X[j] 
        dc += error[j] 

    dm = dm*(2/n)
    dc = dc * (2/n)

    m = m - learning_rate * dm 
    c = c - learning_rate * dc


print("Slope (m):", m) 
print("Intercept (c):", c) 


X_test_np = X_test["Square_Footage"].values 
X_test_np = (X_test_np - X_mean) / X_std 

y_pred_test = m * X_test_np + c 

print("First 10 Prediction:") 
print(y_pred_test[:10])

Slope (m): 251094.5278592626
Intercept (c): 618576.0544203827
First 10 Prediction:
[ 858863.24859834  517515.44416559  998450.83489986 1043375.57531874
  785459.43166391  773426.01905171  984411.85351896  881927.28943839
  812534.61004136  905191.88715531]

---
## Question 4 (10 Marks)

Build a **ColumnTransformer** that applies:
- `StandardScaler` on numerical columns: `Square_Footage`, `Num_Bedrooms`, `Num_Bathrooms`
- `OneHotEncoder` on categorical column: `Neighborhood_Quality`

In [129]:
numerical_features = ["Square_Footage", "Num_Bedrooms", "Num_Bathrooms"]
categorical_features = ["Neighborhood_Quality"]

preprocessor = ColumnTransformer(
    transformers = [
        ("num", StandardScaler(), numerical_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)
preprocessor

ColumnTransformer(transformers=[('num', StandardScaler(),
                                 ['Square_Footage', 'Num_Bedrooms',
                                  'Num_Bathrooms']),
                                ('cat', OneHotEncoder(handle_unknown='ignore'),
                                 ['Neighborhood_Quality'])])

## Question 5 (20 Marks)

Build a complete **Pipeline** using Scikit-Learn that includes:
- The `ColumnTransformer`
- `SGDRegressor` as the final estimator
- Train the pipeline and evaluate using RMSE and R² score
- Print predicted vs actual values for the first 10 test samples

In [130]:
sgd_pipeline = Pipeline(
    steps = [
        ("preprocessor",preprocessor), 
        ("model", SGDRegressor(max_iter=5000, eta0=0.01, random_state=42))
    ]
)

sgd_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Square_Footage',
                                                   'Num_Bedrooms',
                                                   'Num_Bathrooms']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Neighborhood_Quality'])])),
                ('model', SGDRegressor(max_iter=5000, random_state=42))])

In [131]:
def evaluate(model, name): 
    y_pred_sgd = model.predict(X_test) 
    

    print(f"Name of the Model : {name}")
    print("--"* 25)
    print("RMSE :", round(np.sqrt(mean_squared_error(y_test, y_pred_sgd)), 4)) 
    print("R2 Score :", round(r2_score(y_test, y_pred_sgd), 4))
   

    return(
        y_pred_sgd,
        np.sqrt(mean_squared_error(y_test, y_pred_sgd)), 
        r2_score(y_test, y_pred_sgd)
    )


y_pred_sgd, sgd_rmse, sgd_r2_score = evaluate(
    sgd_pipeline, 
    "SGD Regression"
)


 
print("_"* 50)
print("Predicted vs Actual :")
print("--"* 15)

df_comp_sgd = pd.DataFrame(
    {
        "Actual": y_test.values[:10], 
        "Predicted": y_pred_sgd[:10]
    }
)
print(df_comp_sgd)

Name of the Model : SGD Regression
--------------------------------------------------
RMSE : 29096.4609
R2 Score : 0.9869
__________________________________________________
Predicted vs Actual :
------------------------------
         Actual     Predicted
0  9.010005e+05  8.513699e+05
1  4.945375e+05  5.073428e+05
2  9.494042e+05  9.858317e+05
3  1.040389e+06  1.022465e+06
4  7.940100e+05  7.598091e+05
5  7.240336e+05  7.656757e+05
6  9.984392e+05  1.004528e+06
7  9.097134e+05  9.035460e+05
8  7.926815e+05  7.971931e+05
9  9.474908e+05  8.886267e+05

---
## Question 6 (20 Marks)

Implement **Multiple Linear Regression** using **Scikit-Learn**:
- The `ColumnTransformer`
- `LinearRegression` as the final estimator
- Train the pipeline and evaluate using RMSE and R² score
- Print predicted vs actual values for the first 10 test samples

In [133]:
lr_pipeline = Pipeline(
    steps = [
        ('preprocessor', preprocessor), 
        ("model", LinearRegression())
    ]
)
lr_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Square_Footage',
                                                   'Num_Bedrooms',
                                                   'Num_Bathrooms']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Neighborhood_Quality'])])),
                ('model', LinearRegression())])

In [134]:
def evaluate(model, name): 
    y_pred_lr = model.predict(X_test) 


    print(f"Name of the Model : {name}")
    print("--"* 27)
    print("RMSE :", round(np.sqrt(mean_squared_error(y_test, y_pred_lr)), 4)) 
    print("R2 Score :", round(r2_score(y_test, y_pred_lr), 4))
   

    return(
        y_pred_lr,
        np.sqrt(mean_squared_error(y_test, y_pred_lr)), 
        r2_score(y_test, y_pred_lr)
    )

y_pred_lr, lr_rmse, lr_r2_score = evaluate(
    lr_pipeline, 
    "Linear Regression"
)



print("_"* 50)
print("Predicted vs Actual :")
print("--"* 15)


df_comp_lr = pd.DataFrame(
    {
        "Actual": y_test.values[:10], 
        "Predicted": y_pred_lr[:10]
    }
)
print(df_comp_lr)

Name of the Model : Linear Regression
------------------------------------------------------
RMSE : 29093.0752
R2 Score : 0.9869
__________________________________________________
Predicted vs Actual :
------------------------------
         Actual     Predicted
0  9.010005e+05  8.514091e+05
1  4.945375e+05  5.076410e+05
2  9.494042e+05  9.859904e+05
3  1.040389e+06  1.022655e+06
4  7.940100e+05  7.606981e+05
5  7.240336e+05  7.657823e+05
6  9.984392e+05  1.005039e+06
7  9.097134e+05  9.034078e+05
8  7.926815e+05  7.979712e+05
9  9.474908e+05  8.888504e+05

---
## Question 7 (10 Marks) (You have to explore the topic and use the equation via Numpy)
### Dont use LLMs , You can use Documentation

Implement **Multiple Linear Regression** using **only NumPy**:
- Pick random 100 datas from the dataset
- Use the Normal Equation: `θ = (XᵀX)⁻¹ Xᵀy`
- Use `Square_Footage`, `Num_Bedrooms`, and `Num_Bathrooms` as features
- Print the learned coefficients (θ values)

In [177]:
df_random = df.sample(n=100, random_state=42) 

features = ["Square_Footage", "Num_Bedrooms", "Num_Bathrooms"] 

X_np = df_random[features].values 
y_np = df_random["House_Price"].values 

X_b = np.c_[np.ones((X_np.shape[0], 1)), X_np] 

theta = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y_np) 

print("Learned Coefficients theta(θ):")
print(f"Intercept: {theta[0]:0.4f}")
print(f"Square_Footage Coefficient: {theta[1]:0.4f}")
print(f"Num_Bedrooms Coefficient: {theta[2]:0.4f}") 
print(f"Num_Bathrooms Coefficient: {theta[3]:0.4f}")

Learned Coefficients theta(θ):
Intercept: 20888.2595
Square_Footage Coefficient: 202.3082
Num_Bedrooms Coefficient: 8303.2810
Num_Bathrooms Coefficient: 3020.3285

In [171]:
df_random = df.sample(n=100, random_state=42)
# Select features
features = ["Square_Footage", "Num_Bedrooms", "Num_Bathrooms"]

X_np = df_random[features].values
y_np = df_random['House_Price'].values

# Add bias column (important)
X_b = np.c_[np.ones((X_np.shape[0], 1)), X_np]

# Normal Equation: θ = (X^T X)^-1 X^T y
theta = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y_np)

print("Learned coefficients (theta):")
print("Intercept:", theta[0])
print("Square_Footage coefficient:", theta[1])
print("Num_Bedrooms coefficient:", theta[2])
print("Num_Bathrooms coefficient:", theta[3])

Learned coefficients (theta):
Intercept: 20888.259452180464
Square_Footage coefficient: 202.30820792026805
Num_Bedrooms coefficient: 8303.281041200251
Num_Bathrooms coefficient: 3020.328521727244

In [165]:
# Question 7
import numpy as np

# 1. Pick random 100 datas from the dataset
random_subset = df.sample(n=100, random_state=42)

# 2. Extract features and target
features = ['Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms']
X_subset = random_subset[features].values
y_subset = random_subset['House_Price'].values

# Add a column of 1s to X_subset to represent the bias/intercept term (x_0 = 1)
m_samples = X_subset.shape[0]
X_b = np.c_[np.ones((m_samples, 1)), X_subset] 

# 3. Use the Normal Equation: θ = (XᵀX)⁻¹ Xᵀy
theta = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y_subset)

# 4. Print the learned coefficients (θ values)
print("Learned Coefficients via Normal Equation:")
print(f"Intercept (θ0)       : {theta[0]:.4f}")
print(f"Square_Footage (θ1)  : {theta[1]:.4f}")
print(f"Num_Bedrooms (θ2)    : {theta[2]:.4f}")
print(f"Num_Bathrooms (θ3)   : {theta[3]:.4f}")

Learned Coefficients via Normal Equation:
Intercept (θ0)       : 20888.2595
Square_Footage (θ1)  : 202.3082
Num_Bedrooms (θ2)    : 8303.2810
Num_Bathrooms (θ3)   : 3020.3285

In [166]:
import numpy as np
import pandas as pd

# Assume your dataset is already loaded in a DataFrame called df
# Example: df = pd.read_csv("house_data.csv")

# Step 1: Randomly sample 100 rows
df_sample = df.sample(n=100, random_state=42)

# Step 2: Select features and target
X = df_sample[["Square_Footage", "Num_Bedrooms", "Num_Bathrooms"]].values
y = df_sample["House_Price"].values

# Step 3: Add intercept column (bias term)
ones = np.ones((X.shape[0], 1))
X_b = np.hstack((ones, X))   # X with bias

# Step 4: Normal Equation
theta = np.linalg.inv(X_b.T @ X_b) @ (X_b.T @ y)

# Step 5: Print coefficients
print("Theta values (Intercept + Coefficients):")
print(theta)

print("\nBreakdown:")
print("Intercept:", theta[0])
print("Square_Footage coefficient:", theta[1])
print("Num_Bedrooms coefficient:", theta[2])
print("Num_Bathrooms coefficient:", theta[3])

Theta values (Intercept + Coefficients):
[20888.25945218   202.30820792  8303.2810412   3020.32852173]

Breakdown:
Intercept: 20888.2594521821
Square_Footage coefficient: 202.3082079202679
Num_Bedrooms coefficient: 8303.281041200024
Num_Bathrooms coefficient: 3020.328521727182

In [140]:
#Q3 
import numpy as np

# Feature
X_train_np = X_train["Square_Footage"].values
y_train_np = y_train.values

# Normalize optional (helps convergence)
X_train_np = (X_train_np - X_train_np.mean()) / X_train_np.std()

# initialize
m = 0
c = 0
lr = 0.01
epochs = 1000

n = len(X_train_np)

for i in range(epochs):
    y_pred = m * X_train_np + c

    dm = (-2/n) * np.sum(X_train_np * (y_train_np - y_pred))
    dc = (-2/n) * np.sum(y_train_np - y_pred)

    m = m - lr * dm
    c = c - lr * dc

print("Learned slope (m):", m)
print("Learned intercept (c):", c)

# Prediction
X_test_np = X_test["Square_Footage"].values
X_test_np = (X_test_np - X_train["Square_Footage"].mean()) / X_train["Square_Footage"].std()

y_pred_test = m * X_test_np + c

print("\nFirst 10 predictions:")
print(y_pred_test[:10])

Learned slope (m): 251094.52743667946
Learned intercept (c): 618576.0533793424

First 10 predictions:
[ 858713.02069635  517578.62592668  998213.3372414  1043109.99084211
  785355.09561662  773329.20625928  984183.13299118  881762.64196457
  812413.34667061  905012.69472208]

In [159]:
import numpy as np

# -----------------------
# Data
# -----------------------
X = X_train["Square_Footage"].values
y = y_train.values

# -----------------------
# Normalize (recommended)
# -----------------------
X_mean = X.mean()
X_std = X.std()
X = (X - X_mean) / X_std

# -----------------------
# Initialize parameters
# -----------------------
m = 0
c = 0

learning_rate = 0.01
epochs = 1000

n = len(X)

# -----------------------
# Batch Gradient Descent
# -----------------------
for i in range(epochs):

    y_pred = m * X + c

    # gradients
    dm = (-2 / n) * np.sum(X * (y - y_pred))
    dc = (-2 / n) * np.sum(y - y_pred)

    # update parameters
    m = m - learning_rate * dm
    c = c - learning_rate * dc

# -----------------------
# Output learned values
# -----------------------
print("Learned slope (m):", m)
print("Learned intercept (c):", c)

# -----------------------
# Prediction on test set
# -----------------------
X_test_np = X_test["Square_Footage"].values
X_test_np = (X_test_np - X_mean) / X_std

y_pred_test = m * X_test_np + c

print("\nFirst 10 predictions:")
print(y_pred_test[:10])

Learned slope (m): 251094.52743667946
Learned intercept (c): 618576.0533793424

First 10 predictions:
[ 858863.2471529   517515.44329463  998450.8332195  1043375.57356278
  785459.43034201  773426.01775007  984411.85186223  881927.28795414
  812534.6086739   905191.8856319 ]

In [160]:
#Q3 
X = X_train["Square_Footage"].values 
y = y_train.values 

X_mean = X.mean() 
X_std = X.std() 
X = (X - X_mean) / X_std 

m = 0 
c = 0 
learning_rate = 0.01 
iterations = 1000
n = len(X)

for i in range(iterations): 
    y_pred = m * X + c

    error = y_pred - y 

    dm = 0
    dc = 0

    # manual loop (your style)
    for j in range(n):
        dm += error[j] * X[j]
        dc += error[j]

    dm = dm * (2/n)
    dc = dc * (2/n)

    # update parameters
    m = m - learning_rate * dm
    c = c - learning_rate * dc


print("Slope (m):", m) 
print("Intercept (c):", c) 


X_test_np = X_test["Square_Footage"].values 
X_test_np = (X_test_np - X_mean) / X_std 

y_pred_test = m * X_test_np + c 

print("First 10 Prediction:") 
print(y_pred_test[:10])

Slope (m): 251094.52743667946
Intercept (c): 618576.0533793424
First 10 Prediction:
[ 858863.2471529   517515.44329463  998450.8332195  1043375.57356278
  785459.43034201  773426.01775007  984411.85186223  881927.28795414
  812534.6086739   905191.8856319 ]

In [161]:
### OR 
 # Question 6

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
import pandas as pd

# Pipeline with ColumnTransformer + LinearRegression
lr_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", LinearRegression())
    ]
)

# Train the model
lr_pipeline.fit(X_train, y_train)

# Prediction
y_pred = lr_pipeline.predict(X_test)

# Evaluation
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("Multiple Linear Regression Results")
print("-" * 40)
print("RMSE :", round(rmse, 4))
print("R² Score :", round(r2, 4))

# Predicted vs Actual (First 10 Samples)
print("\nPredicted vs Actual Values (First 10 Test Samples)")
print("-" * 40)

comparison_df = pd.DataFrame({
    "Actual": y_test.values[:10],
    "Predicted": y_pred[:10]
})

print(comparison_df)

Multiple Linear Regression Results
----------------------------------------
RMSE : 29093.0752
R² Score : 0.9869

Predicted vs Actual Values (First 10 Test Samples)
----------------------------------------
         Actual     Predicted
0  9.010005e+05  8.514091e+05
1  4.945375e+05  5.076410e+05
2  9.494042e+05  9.859904e+05
3  1.040389e+06  1.022655e+06
4  7.940100e+05  7.606981e+05
5  7.240336e+05  7.657823e+05
6  9.984392e+05  1.005039e+06
7  9.097134e+05  9.034078e+05
8  7.926815e+05  7.979712e+05
9  9.474908e+05  8.888504e+05